<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByRoles($role)
    {
        $er=$this->createQueryBuilder('c')
            ->where('c.roles LIKE :role')
            ->setParameter('role',$role);
        $result = $er->getQuery()->getResult();

        return $result;

    }
}
